(() => {
  "use strict";
  const protocol = self.LifeOSOfflineProtocol;
  const { BundleSyncTransport, DirectLocalSyncTransport } = self.LifeOSSyncTransports;
  const { secureUuid, initializeCaptureRuntime } = self.LifeOSCaptureRuntime;
  const { t, setLocale, getLocale, formatDate } = self.LifeOSCaptureI18n;
  const { open: openDb, get, all, put, putEventWithAttachments, remove, clearBatch } = self.LifeOSCaptureStore;
  const bundleTransport = new BundleSyncTransport();
  const captureTypes = ["mood", "meal", "habit", "task", "note", "journal", "english", "workout", "sleep", "nap"];
  const icons = { mood:"☺", meal:"⌁", habit:"✓", task:"□", note:"✎", journal:"▤", english:"A", workout:"◇", sleep:"☾", nap:"◐" };
  const state = { view:"today", computer:"unpaired", lastErrorCode:null, syncPreview:null, syncing:false, diagnostics:{ indexeddb:"checking", secure:isSecureContext?"yes":"no", serviceWorker:"checking", offlineShell:"checking", device:"checking", storageError:"none" } };
  let toastTimer;
  const $ = selector => document.querySelector(selector);
  const esc = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[character]);
  const localDate = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
  const localDateTimeInput = (date = new Date()) => `${localDate(date)}T${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`;
  const localTime = value => formatDate(new Date(value), { hour:"2-digit", minute:"2-digit", hour12:false });
  const uuid = secureUuid;

  async function getDeviceId() { let row = await get("state", "deviceId"); if (!row) { row = { key:"deviceId", value:uuid() }; await put("state", row); } return row.value; }
  async function pairingState() { return (await get("state", "localSync"))?.value || null; }
  async function savePairing(value) { await put("state", { key:"localSync", value }); }
  function directTransport(pairing) { return new DirectLocalSyncTransport(pairing.hostUrl, pairing.syncToken); }
  function splitTags(value) { return String(value || "").split(/[,，]/).map(item => item.trim()).filter(Boolean).slice(0,20); }
  function valueOf(form, name) { return new FormData(form).get(name)?.toString().trim() || ""; }
  function toast(message) { const node = $("#toast"); node.textContent = message; node.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => node.classList.remove("show"), 2600); }
  function userError(error, fallback = "genericError") {
    const code = error?.code || (error?.name === "AbortError" ? "network_error" : /failed to fetch|network|load failed/i.test(error?.message || "") ? "secure_connection_failed" : "unknown_error");
    state.lastErrorCode = code;
    const keys = { origin_rejected:"originRejected", invalid_pairing_code:"pairingInvalid", pairing_invalid:"pairingInvalid", pairing_code_expired:"pairingExpired", pairing_revoked:"pairingRevoked", unauthorized:"pairingRevoked", secure_connection_failed:"secureConnectionFailed", network_error:"networkError", server_mismatch:"serverMismatch" };
    return t(keys[code] || fallback);
  }
  function field(label, name, type = "text", options = {}) {
    const required = options.required ? "required" : ""; const full = options.full ? " full" : "";
    if (type === "textarea") return `<label class="field${full}"><span>${esc(label)}</span><textarea name="${esc(name)}" ${required} maxlength="${options.max || 10000}" placeholder="${esc(options.placeholder || "")}"></textarea></label>`;
    if (type === "select") return `<label class="field${full}"><span>${esc(label)}</span><select name="${esc(name)}">${options.options.map(option => `<option value="${esc(option.value)}">${esc(option.label)}</option>`).join("")}</select></label>`;
    return `<label class="field${full}"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" ${required} ${options.min != null?`min="${options.min}"`:""} ${options.max != null?`max="${options.max}"`:""} value="${esc(options.value || "")}" placeholder="${esc(options.placeholder || "")}"></label>`;
  }
  const submitButton = label => `<button class="button primary wide" type="submit">${esc(label)}</button>`;

  async function addEvent(type, payload, occurredAt = new Date(), attachmentRecords = []) {
    const now = new Date().toISOString();
    const event = { id:uuid(), deviceId:await getDeviceId(), type, payload, occurredAt:occurredAt.toISOString(), createdAt:now, version:1 };
    if (!protocol.validEvent(event)) throw new Error("invalid_event");
    if (attachmentRecords.length) await putEventWithAttachments(event, attachmentRecords); else await put("events", event); await refreshUI(); return event;
  }

  function setView(view) {
    state.view = view;
    document.querySelectorAll("[data-view-panel]").forEach(panel => panel.classList.toggle("active", panel.dataset.viewPanel === view));
    document.querySelectorAll("[data-view]").forEach(button => { const active = button.dataset.view === view; button.classList.toggle("active", active); button.setAttribute("aria-current", active ? "page" : "false"); });
    $("#page-title").textContent = t(view);
    scrollTo({ top:0, behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth" });
  }

  function renderNavigation() {
    const items = [["today","⌂","navToday"],["capture","＋","navCapture"],["pending","↥","navPending"],["settings","⚙","navSettings"]];
    $("#bottom-nav").setAttribute("aria-label", t("navigation"));
    $("#bottom-nav").innerHTML = items.map(([view,icon,key]) => `<button type="button" data-view="${view}" class="nav-item ${state.view===view?"active":""}"><span class="nav-icon">${icon}</span><span>${esc(t(key))}</span></button>`).join("");
    $("#bottom-nav").querySelectorAll("[data-view]").forEach(button => button.addEventListener("click", () => setView(button.dataset.view)));
  }

  function quickCard(type, secondary = false) { return `<button type="button" class="capture-card${secondary?" secondary-card":""}" data-tab="${type}" data-capture="${type}"><span class="capture-icon">${icons[type]}</span><span>${esc(t(type))}</span></button>`; }
  function activeLabel(kind) { return t({english:"studying",workout:"training",sleep:"sleeping",nap:"napping"}[kind]); }
  function elapsed(startedAt) { const seconds = Math.max(0, Math.floor((Date.now()-Date.parse(startedAt))/1000)); return `${String(Math.floor(seconds/3600)).padStart(2,"0")}:${String(Math.floor(seconds%3600/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`; }

  async function renderToday(events, timer) {
    const todayEvents = events.filter(event => localDate(new Date(event.occurredAt)) === localDate()).sort((a,b) => b.occurredAt.localeCompare(a.occurredAt));
    const active = timer ? `<article class="active-card"><div><span class="section-kicker">${esc(t("activeSession"))}</span><h2>${esc(activeLabel(timer.kind))}</h2>${timer.metadata?.courseName?`<p>${esc(timer.metadata.courseName)}</p>`:""}${timer.metadata?.bodyPart?`<p>${esc(localizePart(timer.metadata.bodyPart))}</p>`:""}<div id="timer-clock" class="timer-clock">${elapsed(timer.startedAt)}</div><span class="meta">${esc(t("startedAt",{time:localTime(timer.startedAt)}))}</span></div><div class="active-actions"><button id="finish-timer" class="button primary" type="button">${esc(timer.kind==="sleep"?t("wakeUp"):timer.kind==="nap"?t("finishNap"):t("finish"))}</button><button id="cancel-timer" class="button quiet" type="button">${esc(t("cancelSession"))}</button></div></article>` : "";
    $("#view-today").innerHTML = `${active}<section class="content-section"><div class="section-title"><div><h2>${esc(t("quickCapture"))}</h2><p>${esc(t("quickCaptureHelp"))}</p></div></div><div class="quick-grid">${["mood","meal","english","workout","sleep","note","habit","task","journal","nap"].map(type=>quickCard(type)).join("")}</div></section><section class="content-section"><div class="section-title"><h2>${esc(t("todayActivity"))}</h2><span class="count-badge">${todayEvents.length}</span></div><div class="activity-list">${todayEvents.length?todayEvents.map(activityRow).join(""):`<div class="empty-state">${esc(t("noTodayActivity"))}</div>`}</div></section>`;
    bindCaptureButtons($("#view-today"));
    $("#finish-timer")?.addEventListener("click", finishTimer);
    $("#cancel-timer")?.addEventListener("click", cancelTimer);
    $("#view-today").querySelectorAll("[data-activity-detail]").forEach(button=>button.addEventListener("click",()=>showEventDetail(todayEvents.find(event=>event.id===button.dataset.activityDetail))));
  }

  function activityRow(event) { const summary = summarize(event); return `<article class="activity-row"><button class="activity-detail" type="button" data-activity-detail="${esc(event.id)}"><span class="activity-time">${esc(localTime(event.occurredAt))}</span><span class="activity-icon">${icons[eventFamily(event.type)] || "·"}</span><span class="activity-copy"><strong>${esc(summary.title)}</strong>${summary.detail?`<small>${esc(summary.detail)}</small>`:""}</span></button></article>`; }
  function eventFamily(type) { return type.split(".")[0] === "meal" ? "meal" : type.split(".")[0]; }
  function summarize(event) {
    const p = event.payload;
    if (event.type === "mood.log") return { title:`${t("mood")} ${p.score}/10`, detail:p.note || "" };
    if (event.type === "meal.update") return { title:t(p.field === "snackCount" ? "snack" : p.field), detail:p.content || p.note || (p.tags?.length ? p.tags.map(tag=>localizeMealTag(tag)).join(" · ") : p.field === "snackCount" ? String(p.value) : "") };
    if (event.type === "habit.complete") return { title:t("habit"), detail:"" };
    if (event.type === "task.create") return { title:t("task"), detail:p.title };
    if (event.type === "note.create") return { title:t("note"), detail:p.content.slice(0,80) };
    if (event.type === "journal.create") return { title:t("journal"), detail:p.title || p.content.slice(0,80) };
    if (event.type === "english.session") return { title:t("english"), detail:`${p.courseName || t("english")} · ${durationText(p)}` };
    if (event.type === "workout.session") return { title:t("workout"), detail:`${localizePart(p.bodyPart)} · ${durationText(p)}` };
    if (event.type === "sleep.session") return { title:t(p.kind), detail:durationText(p) };
    return { title:event.type, detail:"" };
  }
  function durationText(payload) { return t("durationMinutes", { count:Math.max(0,Math.round((Date.parse(payload.endedAt)-Date.parse(payload.startedAt))/60000)) }); }

  function renderCapture() {
    const groups = [["daily",["mood","meal","habit"]],["learning",["english","task"]],["health",["workout","sleep","nap"]],["writing",["note","journal"]]];
    $("#view-capture").innerHTML = `<p class="view-intro">${esc(t("captureSubtitle"))}</p>${groups.map(([label,types])=>`<section class="capture-group"><h2>${esc(t(label))}</h2><div class="capture-list">${types.map(type=>`<button type="button" data-tab="${type}" data-capture="${type}"><span class="capture-icon">${icons[type]}</span><span class="capture-directory-copy"><strong>${esc(t(type))}</strong><small>${esc(t(`${type}Help`))}</small></span><span class="chevron">›</span></button>`).join("")}</div></section>`).join("")}`;
    bindCaptureButtons($("#view-capture"));
  }
  function bindCaptureButtons(root) { root.querySelectorAll("[data-capture]").forEach(button => button.addEventListener("click", () => openCapture(button.dataset.capture))); }

  async function openCapture(type) {
    if (!captureTypes.includes(type)) return;
    const profile = (await get("state","profile"))?.value;
    $("#sheet-title").textContent = t(type); $("#sheet-close").textContent = "×"; $("#sheet-close").setAttribute("aria-label",t("close"));
    const body = $("#sheet-body"); body.innerHTML = captureForm(type,profile); const sheet = $("#capture-sheet"); sheet.showModal();
    $("#capture-form")?.addEventListener("submit", event => saveCaptureForm(event,type));
    body.querySelectorAll("[data-score]").forEach(button => button.addEventListener("click", () => { body.querySelectorAll("[data-score]").forEach(item=>item.classList.remove("selected")); button.classList.add("selected"); body.querySelector("[name=score]").value=button.dataset.score; }));
    body.querySelectorAll("[data-meal-type]").forEach(button => button.addEventListener("click", () => { body.querySelectorAll("[data-meal-type]").forEach(item=>item.classList.remove("selected")); button.classList.add("selected"); body.querySelector("[name=mealType]").value=button.dataset.mealType; }));
    body.querySelectorAll("[data-meal-tag]").forEach(button => button.addEventListener("click", () => button.classList.toggle("selected")));
    body.querySelectorAll("[data-fullness]").forEach(button => button.addEventListener("click", () => { body.querySelectorAll("[data-fullness]").forEach(item=>item.classList.remove("selected")); button.classList.add("selected"); body.querySelector("[name=fullness]").value=button.dataset.fullness; }));
    body.querySelectorAll("[data-habit]").forEach(button => button.addEventListener("click", () => saveHabit(button.dataset.habit)));
    $("#sheet-import-profile")?.addEventListener("click",()=>{ sheet.close(); $("#profile-file").click(); });
  }

  function captureForm(type,profile) {
    if (type === "mood") return `<form id="capture-form"><p class="sheet-question">${esc(t("moodQuestion"))}</p><div class="score-grid">${Array.from({length:10},(_,i)=>`<button type="button" data-score="${i+1}">${i+1}</button>`).join("")}</div><input type="hidden" name="score">${field(t("moodTags"),"tags","text",{placeholder:t("moodTagsPlaceholder")})}${field(t("moodNote"),"note","textarea",{full:true})}${submitButton(t("moodSave"))}</form>`;
    if (type === "meal") return `<form id="capture-form"><p class="sheet-question">${esc(t("mealQuestion"))}</p><div class="meal-type-grid">${["breakfast","lunch","dinner","snack"].map(item=>`<button class="meal-chip" type="button" data-meal-type="${item}">${esc(t(item))}</button>`).join("")}</div><input type="hidden" name="mealType">${field(t("mealContent"),"content","textarea",{required:true,full:true,max:10000,placeholder:t("mealContentPlaceholder")})}<div class="field"><span>${esc(t("mealTags"))}</span><div class="meal-tag-grid">${["light","greasy","highProtein","highSugar","takeaway","canteen","home"].map(item=>`<button class="meal-tag" type="button" data-meal-tag="${item}">${esc(t(`mealTag_${item}`))}</button>`).join("")}</div></div><div class="field"><span>${esc(t("fullnessOptional"))}</span><div class="fullness-grid">${[1,2,3,4,5].map(value=>`<button type="button" data-fullness="${value}">${value}</button>`).join("")}</div><div class="fullness-labels"><span>${esc(t("notFull"))}</span><span>${esc(t("veryFull"))}</span></div><input type="hidden" name="fullness"></div>${field(t("mealTime"),"mealAt","datetime-local",{required:true,value:localDateTimeInput()})}${field(t("mealNote"),"note","textarea",{full:true,max:10000,placeholder:t("mealNotePlaceholder")})}<label class="field"><span>${esc(t("mealPhoto"))}</span><input name="mealPhoto" type="file" accept="image/jpeg,image/png,image/webp"></label>${submitButton(t("mealSave"))}</form>`;
    if (type === "habit") return profile?.habits?.length ? `<div class="habit-options">${profile.habits.map(habit=>`<button class="habit-button" type="button" data-habit="${esc(habit.id)}"><span>✓</span>${esc(habit.name)}</button>`).join("")}</div>` : `<div class="empty-state prominent"><strong>${esc(t("habitNoProfile"))}</strong><p>${esc(t("habitNoProfileHelp"))}</p><button id="sheet-import-profile" class="button primary" type="button">${esc(t("importProfile"))}</button></div>`;
    if (type === "task") return `<form id="capture-form">${field(t("taskName"),"title","text",{required:true,full:true})}${field(t("dateOptional"),"dueDate","date")}${field(t("noteOptional"),"description","textarea",{full:true})}${submitButton(t("taskSave"))}</form>`;
    if (type === "note") return `<form id="capture-form">${field("","content","textarea",{required:true,full:true,max:100000,placeholder:t("quickNotePlaceholder")})}${submitButton(t("noteSave"))}</form>`;
    if (type === "journal") return `<form id="capture-form">${field(t("titleOptional"),"title","text",{full:true})}${field(t("content"),"content","textarea",{required:true,full:true,max:100000})}${field(t("tagsOptional"),"tags","text",{full:true})}${submitButton(t("journalSave"))}</form>`;
    if (type === "english") return `<form id="capture-form">${field(t("course"),"courseName","text",{required:true,full:true,placeholder:t("coursePlaceholder")})}${field(t("category"),"category","select",{full:true,options:englishCategories()})}${submitButton(t("startLearning"))}</form>`;
    if (type === "workout") return `<form id="capture-form">${field(t("trainingPart"),"bodyPart","select",{full:true,options:workoutParts(profile)})}${submitButton(t("startWorkout"))}</form>`;
    return `<form id="capture-form"><div class="one-tap-start"><span class="capture-icon large">${icons[type]}</span><p>${esc(type==="sleep"?t("startSleep"):t("startNap"))}</p></div>${submitButton(type==="sleep"?t("startSleep"):t("startNap"))}</form>`;
  }
  function englishCategories(){return [["course","courseCategory"],["listening","listening"],["speaking","speaking"],["reading","reading"],["vocabulary","vocabulary"],["writing","writingCategory"],["youtube","youtube"],["podcast","podcast"],["other","other"]].map(([value,key])=>({value,label:t(key)}));}
  function workoutParts(profile){const fallback=["Chest","Back","Shoulders","Arms","Legs","Core","Full body","Cardio","Other"];return (profile?.workoutBodyParts?.length?profile.workoutBodyParts:fallback).map(value=>({value,label:localizePart(value)}));}
  function localizePart(value){const key={chest:"chest",back:"back",shoulders:"shoulders",arms:"arms",legs:"legs",core:"core","full body":"fullBody",cardio:"cardio",other:"other"}[String(value).toLowerCase()];return key?t(key):value;}

  async function saveCaptureForm(event,type) {
    event.preventDefault(); const form=event.currentTarget; if(!form.reportValidity())return;
    try {
      if(type==="mood"){const score=Number(valueOf(form,"score"));if(!score){toast(t("moodRequired"));return;}await addEvent("mood.log",{score,tags:splitTags(valueOf(form,"tags")),note:valueOf(form,"note")||undefined});}
      else if(type==="meal"){if(!await saveMeal(form))return;}
      else if(type==="task")await addEvent("task.create",{title:valueOf(form,"title"),description:valueOf(form,"description")||undefined,dueDate:valueOf(form,"dueDate")||undefined});
      else if(type==="note")await addEvent("note.create",{content:valueOf(form,"content"),tags:[]});
      else if(type==="journal")await addEvent("journal.create",{date:localDate(),title:valueOf(form,"title")||undefined,content:valueOf(form,"content"),tags:splitTags(valueOf(form,"tags"))});
      else await startTimer(type,{courseName:valueOf(form,"courseName")||undefined,category:valueOf(form,"category")||undefined,bodyPart:valueOf(form,"bodyPart")||undefined});
      $("#capture-sheet").close();
      toast(t(type==="task"?"taskSaved":type==="note"?"noteSaved":type==="journal"?"journalSaved":type==="meal"?"mealSaved":"savedOnDevice"));
    } catch(error){toast(userError(error));}
  }
  async function saveMeal(form){const mealType=valueOf(form,"mealType");if(!mealType){toast(t("mealTypeRequired"));return false;}const occurredAt=new Date(valueOf(form,"mealAt"));const date=localDate(occurredAt);const events=await all("events");const field=mealType==="snack"?"snackCount":mealType;const previous=field==="snackCount"?events.filter(event=>event.type==="meal.update"&&event.payload.date===date&&event.payload.field==="snackCount").sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]?.payload.value||0:0;const file=form.querySelector("[name=mealPhoto]")?.files?.[0];const photo=file?await self.LifeOSCaptureAttachments.prepare(file):null;const reference=photo?{id:photo.id,sha256:photo.sha256,mimeType:photo.mimeType,byteSize:photo.byteSize,width:photo.width,height:photo.height,originalName:photo.originalName}:null;const payload={date,field,value:field==="snackCount"?previous+1:true,content:valueOf(form,"content"),note:valueOf(form,"note")||undefined,tags:[...form.querySelectorAll("[data-meal-tag].selected")].map(button=>button.dataset.mealTag),fullness:valueOf(form,"fullness")?Number(valueOf(form,"fullness")):undefined,attachments:reference?[reference]:undefined};await addEvent("meal.update",payload,occurredAt,photo?[photo]:[]);return true;}
  function localizeMealTag(value){return t(`mealTag_${value}`);}
  async function saveHabit(habitId){await addEvent("habit.complete",{habitId,date:localDate()});$("#capture-sheet").close();toast(t("habitDone"));}

  async function startTimer(kind,metadata={}){if(await get("state","activeTimer")){toast(t("timerAlreadyRunning"));return;}await put("state",{key:"activeTimer",value:{kind,startedAt:new Date().toISOString(),metadata:Object.fromEntries(Object.entries(metadata).filter(([,value])=>value))}});await refreshUI();}
  async function cancelTimer(){if(!confirm(t("cancelSessionConfirm")))return;await remove("state","activeTimer");await refreshUI();}
  async function finishTimer(){const row=await get("state","activeTimer");if(!row)return;const timer=row.value;const endedAt=new Date().toISOString();$("#finish-title").textContent=t({english:"finishEnglish",workout:"finishWorkout",sleep:"finishSleep",nap:"finishNapTitle"}[timer.kind]);$("#finish-keep").textContent=t("keepRunning");$("#finish-save").textContent=t("saveSession");$("#finish-form .icon-button").textContent="×";$("#finish-form .icon-button").setAttribute("aria-label",t("close"));const rating=timer.kind==="english"?"":`<div class="field"><span>${esc(t("qualityOptional"))}</span><div class="quality-grid">${[1,2,3,4,5].map(value=>`<button type="button" data-quality="${value}">${value}</button>`).join("")}</div><input type="hidden" name="quality"></div>`;$("#finish-fields").innerHTML=`<div class="session-summary"><strong>${esc(durationText({startedAt:timer.startedAt,endedAt}))}</strong><span>${esc(localTime(timer.startedAt))}–${esc(localTime(endedAt))}</span></div>${rating}${field(t("sessionNoteOptional"),"note","textarea",{full:true})}`;$("#finish-fields").querySelectorAll("[data-quality]").forEach(button=>button.addEventListener("click",()=>{$("#finish-fields").querySelectorAll("[data-quality]").forEach(item=>item.classList.remove("selected"));button.classList.add("selected");$("#finish-fields [name=quality]").value=button.dataset.quality;}));$("#finish-dialog").showModal();$("#finish-save").onclick=async click=>{click.preventDefault();const form=$("#finish-form");const note=valueOf(form,"note")||undefined;const quality=valueOf(form,"quality")?Number(valueOf(form,"quality")):undefined;let type,payload;if(timer.kind==="english"){type="english.session";payload={startedAt:timer.startedAt,endedAt,courseName:timer.metadata?.courseName||t("english"),category:timer.metadata?.category||"other",note};}else if(timer.kind==="workout"){type="workout.session";payload={startedAt:timer.startedAt,endedAt,bodyPart:timer.metadata?.bodyPart||"Other",quality,note};}else{type="sleep.session";payload={kind:timer.kind,startedAt:timer.startedAt,endedAt,quality,note};}await addEvent(type,payload,new Date(endedAt));await remove("state","activeTimer");$("#finish-dialog").close();await refreshUI();toast(t("sessionSaved"));};}

  async function renderPending(events,batches){const pairing=await pairingState();const online=state.computer==="online";const headline=events.length?t("pendingHeadline",{count:events.length}):t("noPending");const help=online?t("syncOnlineReady"):pairing?t("syncOfflineHelp"):t("syncUnpairedHelp");const action=events.length&&online?`<button id="sync-now" class="button primary wide" type="button" ${state.syncing?"disabled":""}>${esc(state.syncing?t("syncing"):t("syncNow"))}</button>`:"";$("#view-pending").innerHTML=`<section class="sync-hero ${online?"online":""}"><span class="status-dot"></span><div><span>${esc(online?t("computerOnline"):pairing?t("computerTemporarilyUnavailable"):t("computerUnpaired"))}</span><h2>${esc(headline)}</h2><p>${esc(help)}</p></div>${action}</section><div id="sync-preview">${renderSyncPreview()}</div><section class="content-section"><div class="section-title"><h2>${esc(t("pendingList"))}</h2><span id="pending-count" class="count-badge">${events.length}</span></div><div id="queue" class="pending-list">${events.length?events.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(pendingRow).join(""):`<div class="empty-state">${esc(t("pendingEmpty"))}</div>`}</div></section><details class="fallback-card"><summary>${esc(t("bundleQuestion"))}</summary><p>${esc(t("bundleHelpRefined"))}</p><div class="stack-actions"><button id="export-button" class="button secondary wide" type="button">${esc(t("exportBundle"))}</button><button id="import-receipt-button" class="button secondary wide" type="button">${esc(t("importReceipt"))}</button></div><div id="batch-area">${renderBatches(batches)}</div><label class="field"><span>${esc(t("manualFallback"))}</span><select id="manual-batch">${batches.length?batches.map(batch=>`<option value="${esc(batch.batchId)}">${esc(formatDate(new Date(batch.exportedAt),{dateStyle:"short",timeStyle:"short"}))} · ${batch.eventCount}</option>`).join(""):`<option value="">${esc(t("noBatches"))}</option>`}</select></label><button id="manual-confirm" class="button quiet wide" type="button" ${batches.length?"":"disabled"}>${esc(t("markSynced"))}</button></details>`;
    $("#sync-now")?.addEventListener("click",()=>beginDirectSync(false));$("#export-button").addEventListener("click",exportBundle);$("#import-receipt-button").addEventListener("click",()=>$("#receipt-file").click());$("#manual-confirm").addEventListener("click",markBatch);$("#queue").querySelectorAll("[data-delete]").forEach(button=>button.addEventListener("click",()=>deletePending(button.dataset.delete)));$("#queue").querySelectorAll("[data-detail]").forEach(button=>button.addEventListener("click",()=>showEventDetail(events.find(event=>event.id===button.dataset.detail))));bindSyncPreview();}
  function pendingRow(event){const summary=summarize(event);return `<article class="pending-row"><span class="activity-icon">${icons[eventFamily(event.type)]||"·"}</span><button type="button" data-detail="${esc(event.id)}"><strong>${esc(summary.title)}</strong><span>${esc(summary.detail)}</span><small>${esc(localTime(event.occurredAt))}</small></button><button class="remove-button" type="button" data-delete="${esc(event.id)}" aria-label="${esc(t("remove"))}">×</button></article>`;}
  function showEventDetail(event){if(!event)return;const summary=summarize(event);$("#sheet-title").textContent=t("detailTitle");$("#sheet-body").innerHTML=`<div class="detail-card"><span>${icons[eventFamily(event.type)]||"·"}</span><h3>${esc(summary.title)}</h3><p>${esc(summary.detail)}</p><small>${esc(formatDate(new Date(event.occurredAt),{dateStyle:"medium",timeStyle:"short"}))}</small></div>`;$("#capture-sheet").showModal();}
  async function deletePending(id){if(!confirm(t("removePendingConfirm")))return;await remove("events",id);await refreshUI();toast(t("removed"));}
  function renderBatches(batches){return batches.map(batch=>`<div class="batch-item">${esc(formatDate(new Date(batch.exportedAt),{dateStyle:"short",timeStyle:"short"}))} · ${batch.eventCount}</div>`).join("");}
  function renderSyncPreview(){if(!state.syncPreview)return"";const preview=state.syncPreview;return `<div class="preview-card"><strong>${esc(t("syncPreview",{count:preview.eventCount,newCount:preview.new}))}</strong><div class="sheet-actions"><button id="cancel-direct" class="button secondary">${esc(t("cancel"))}</button><button id="confirm-direct" class="button primary">${esc(t("syncNow"))}</button></div></div>`;}
  function bindSyncPreview(){$("#cancel-direct")?.addEventListener("click",()=>{state.syncPreview=null;refreshUI();});$("#confirm-direct")?.addEventListener("click",commitDirectSync);}

  async function renderSettings(profile,pairing,autoSync){const profileText=profile?t("personalizedProfile",{time:formatDate(new Date(profile.generatedAt),{dateStyle:"short",timeStyle:"short"})}):t("defaultProfile");const profileHelp=profile?t("personalizedProfileHelp",{count:profile.habits.length}):t("defaultProfileHelp");$("#view-settings").innerHTML=`<section class="settings-card"><h2>${esc(t("language"))}</h2><div class="segmented"><button type="button" data-locale="zh-CN" class="${getLocale()==="zh-CN"?"active":""}">${esc(t("simplifiedChinese"))}</button><button type="button" data-locale="en" class="${getLocale()==="en"?"active":""}">${esc(t("englishLanguage"))}</button></div></section><section class="settings-card"><div class="settings-row"><div><h2>${esc(t("computerConnection"))}</h2><p>${esc(pairing?`${t("connected")} · ${pairing.hostUrl}`:t("notConnected"))}</p></div><span class="state-label">${esc(state.computer==="online"?t("computerOnline"):t("computerOffline"))}</span></div><button id="pair-button" class="button secondary wide" type="button">${esc(pairing?t("updateComputer"):t("connectComputer"))}</button>${pairing&&state.computer==="online"?`<a id="open-lifeos" class="button quiet wide" href="${esc(pairing.hostUrl)}/today" target="_blank" rel="noopener">${esc(t("openFullLifeOS"))}</a>`:""}</section><section class="settings-card"><label class="switch-row"><div><h2>${esc(t("autoSync"))}</h2><p>${esc(t("autoSyncHelp"))}</p></div><input id="auto-sync" type="checkbox" ${autoSync?"checked":""}></label></section><section class="settings-card"><h2>${esc(t("captureProfile"))}</h2><p id="profile-status"><strong>${esc(profileText)}</strong><br><span>${esc(profileHelp)}</span></p><button id="import-profile-button" class="button secondary wide" type="button">${esc(t("importPersonalizedProfile"))}</button></section><section class="settings-card"><h2>${esc(t("dataSafety"))}</h2><p>${esc(t("dataSafetyText"))}</p><button id="settings-export" class="button secondary wide" type="button">${esc(t("exportBundle"))}</button><small>${esc(t("storageWarning"))}</small></section><details class="settings-card advanced"><summary>${esc(t("advanced"))}</summary><div class="advanced-content">${pairing?`<div class="diagnostic-row"><span>${esc(t("serverId"))}</span><span>${esc(pairing.serverId)}</span></div>`:""}<h3>${esc(t("diagnostics"))}</h3><div class="diagnostic-grid">${diagnosticRows()}</div></div></details>`;
    $("#view-settings").querySelectorAll("[data-locale]").forEach(button=>button.addEventListener("click",()=>setLocale(button.dataset.locale)));$("#pair-button").addEventListener("click",openPairDialog);$("#auto-sync").addEventListener("change",async event=>{await put("state",{key:"autoSync",value:event.target.checked});if(event.target.checked)await checkComputer({retry:false,auto:true});});$("#import-profile-button").addEventListener("click",()=>$("#profile-file").click());$("#settings-export").addEventListener("click",exportBundle);}
  function diagnosticRows(){const rows=[["indexedDb","indexeddb"],["secureContext","secure"],["serviceWorker","serviceWorker"],["offlineShell","offlineShell"],["deviceId","device"],["computer","computer"],["pendingDiagnostic","pending"],["storageError","storageError"]];return rows.map(([label,key])=>`<div class="diagnostic-row"><span>${esc(t(label))}</span><span id="diagnostic-${key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}">${esc(diagnosticText(key))}</span></div>`).join("")+`<div class="diagnostic-row"><span>${esc(t("errorCode"))}</span><span>${esc(state.lastErrorCode||t("none"))}</span></div>`;}
  function diagnosticText(key){if(key==="computer")return state.computer==="online"?t("computerOnline"):t("computerOffline");if(key==="pending")return String(state.pending||0);const value=state.diagnostics[key];return t({available:"available",unavailable:"unavailable",yes:"yes",no:"no",ready:"ready",active:"activated",checking:"checking",none:"none"}[value]||value||"none");}

  async function refreshUI(){const [events,timerRow,profileRow,pairing,batches,autoRow]=await Promise.all([all("events"),get("state","activeTimer"),get("state","profile"),pairingState(),all("batches"),get("state","autoSync")]);state.pending=events.length;$("#today-date").textContent=formatDate(new Date(),getLocale()==="zh-CN"?{month:"long",day:"numeric",weekday:"long"}:{month:"short",day:"numeric",weekday:"long"});$("#page-title").textContent=t(state.view);const status=$("#header-status");status.classList.toggle("online",state.computer==="online");status.innerHTML=`<span class="status-dot"></span><span>${esc(state.computer==="online"?t("computerOnline"):state.computer==="unpaired"?t("computerUnpaired"):t("computerOffline"))}<small>${esc(events.length?t("pendingCount",{count:events.length}):t("allSynced"))}</small></span>`;status.onclick=()=>setView("pending");renderNavigation();await renderToday(events,timerRow?.value);renderCapture();await renderPending(events,batches.sort((a,b)=>b.exportedAt.localeCompare(a.exportedAt)));await renderSettings(profileRow?.value,pairing,autoRow?.value===true);setView(state.view);}

  async function checkComputer({retry=true,auto=false}={}){const pairing=await pairingState();if(!pairing){state.computer="unpaired";await refreshUI();return false;}try{const health=await directTransport(pairing).health(retry?3:1);if(health.serverId!==pairing.serverId){const error=new Error("server mismatch");error.code="server_mismatch";throw error;}pairing.lastSeenAt=new Date().toISOString();await savePairing(pairing);state.computer="online";await refreshUI();if(auto&&(await get("state","autoSync"))?.value===true&&(await all("events")).length)await beginDirectSync(true);return true;}catch(error){state.computer="offline";userError(error,"secureConnectionFailed");await refreshUI();return false;}}
  let directSyncPromise=null;
  async function beginDirectSync(auto=false){if(directSyncPromise)return directSyncPromise;directSyncPromise=runDirectSync(auto);try{return await directSyncPromise;}finally{directSyncPromise=null;}}
  async function runDirectSync(auto=false){try{const pairing=await pairingState();if(!pairing){setView("settings");return;}const events=(await all("events")).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));if(!events.length){toast(t("noPending"));return;}const attachmentIds=[...new Set(events.flatMap(event=>event.type==="meal.update"?(event.payload.attachments||[]).map(item=>item.id):[]))];const stored=await Promise.all(attachmentIds.map(id=>get("attachments",id)));const refs=stored.filter(Boolean).map(item=>{const reference={...item};delete reference.blob;return reference;});const bundle=refs.length?bundleTransport.createBundleV2(events,await getDeviceId(),refs):bundleTransport.createBundle(events,await getDeviceId());if(refs.length){const status=await directTransport(pairing).prepareAttachments(refs);for(const item of status.attachments.filter(item=>item.status==="missing")){const local=stored.find(value=>value?.id===item.id);if(local)await directTransport(pairing).uploadAttachment(local);}}const batch={batchId:bundle.meta.batchId,eventIds:events.map(event=>event.id),attachmentIds,exportedAt:bundle.meta.exportedAt,eventCount:events.length};await put("batches",batch);const preview=await directTransport(pairing).preview(bundle);state.syncPreview={...preview,bundle,batch};await refreshUI();if(auto)await commitDirectSync();}catch(error){toast(`${userError(error,"secureConnectionFailed")} ${t("useBundle")}`);}}
  async function commitDirectSync(){const current=state.syncPreview;if(!current||state.syncing)return;state.syncing=true;await refreshUI();try{const pairing=await pairingState();const result=await directTransport(pairing).commit(current.bundle);if(!protocol.receiptMatchesBatch(result.receipt,current.batch,await getDeviceId()))throw new Error("receipt mismatch");await clearBatch(current.batch);pairing.lastSyncAt=new Date().toISOString();await savePairing(pairing);state.syncPreview=null;toast(t("syncedCount",{count:current.batch.eventCount}));}catch(error){toast(`${userError(error,"secureConnectionFailed")} ${t("useBundle")}`);}finally{state.syncing=false;await refreshUI();}}

  async function exportBundle(){const events=(await all("events")).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));if(!events.length){toast(t("noEventsToExport"));return;}try{const attachmentIds=[...new Set(events.flatMap(event=>event.type==="meal.update"?(event.payload.attachments||[]).map(item=>item.id):[]))];const stored=await Promise.all(attachmentIds.map(id=>get("attachments",id)));const refs=stored.filter(Boolean).map(item=>{const reference={...item};delete reference.blob;return reference;});const bundle=refs.length?bundleTransport.createBundleV2(events,await getDeviceId(),refs):bundleTransport.createBundle(events,await getDeviceId());const batch={batchId:bundle.meta.batchId,eventIds:events.map(event=>event.id),attachmentIds,exportedAt:bundle.meta.exportedAt,eventCount:events.length};await put("batches",batch);if(refs.length){const entries=[{path:"manifest.json",content:JSON.stringify({app:"LifeOS",kind:"offline-sync",version:2,batchId:bundle.meta.batchId,deviceId:bundle.meta.deviceId,exportedAt:bundle.meta.exportedAt,attachments:refs})},{path:"events.json",content:JSON.stringify(bundle.events)}];for(const item of stored.filter(Boolean))entries.push({path:`attachments/${item.id}.${item.mimeType==="image/jpeg"?"jpg":item.mimeType.split("/")[1]}`,content:new Uint8Array(await item.blob.arrayBuffer())});downloadBlob(self.LifeOSCaptureZip.create(entries),`lifeos-sync-${stamp(new Date())}.zip`);}else downloadJson(bundle,`lifeos-sync-${stamp(new Date())}.json`);await refreshUI();toast(t("exported"));}catch(error){toast(userError(error));}}
  function downloadJson(data,filename){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  function downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  function stamp(date){return`${localDate(date)}-${String(date.getHours()).padStart(2,"0")}${String(date.getMinutes()).padStart(2,"0")}${String(date.getSeconds()).padStart(2,"0")}`;}
  async function parseFile(file){if(!file||file.size>2*1024*1024){const error=new Error();error.code="file_too_large";throw error;}return JSON.parse(await file.text());}
  async function importProfile(file){try{const profile=await parseFile(file);if(!protocol.validProfile(profile))throw new Error("invalid profile");await put("state",{key:"profile",value:profile});await refreshUI();toast(t("profileImportSuccess"));}catch(error){toast(t(error.code==="file_too_large"?"fileTooLarge":"invalidFile"));}finally{$("#profile-file").value="";}}
  async function importReceipt(file){try{const receipt=await parseFile(file);const batch=await get("batches",receipt?.meta?.batchId);if(!batch||!protocol.receiptMatchesBatch(receipt,batch,await getDeviceId()))throw new Error("invalid receipt");await clearBatch(batch);await refreshUI();toast(t("receiptConfirmed",{count:batch.eventCount}));}catch{toast(t("receiptInvalid"));}finally{$("#receipt-file").value="";}}
  async function markBatch(){const batch=await get("batches",$("#manual-batch").value);if(!batch)return;if(!confirm(t("deleteBatchConfirm")))return;if(prompt(t("manualConfirmPrompt"))!=="SYNCED"){toast(t("batchKept"));return;}await clearBatch(batch);await refreshUI();toast(t("receiptConfirmed",{count:batch.eventCount}));}

  async function openPairDialog(){const pairing=await pairingState();$("#pair-title").textContent=t("pairTitle");$("#pair-fields").innerHTML=`${field(t("lifeosComputerUrl"),"hostUrl","url",{required:true,full:true,value:pairing?.hostUrl||"",placeholder:"https://172.20.10.6:3443"})}${field(t("serverIdLabel"),"serverId","text",{required:true,full:true,value:pairing?.serverId||""})}${field(t("pairingCode"),"code","text",{full:true})}<p class="hint">${esc(t("pairingCodeHelp"))}</p>`;$("#pair-save").textContent=t("pairSave");$("#pair-cancel").textContent=t("cancel");$("#pair-form .icon-button").textContent="×";$("#pair-form .icon-button").setAttribute("aria-label",t("close"));$("#pair-dialog").showModal();}
  async function pairComputer(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const button=$("#pair-save");button.disabled=true;try{const hostUrl=valueOf(form,"hostUrl"),serverId=valueOf(form,"serverId"),code=valueOf(form,"code"),existing=await pairingState(),transport=new DirectLocalSyncTransport(hostUrl);const health=await transport.health(1);if(health.serverId!==serverId){const error=new Error();error.code="server_mismatch";throw error;}if(!code){if(!existing?.syncToken||existing.serverId!==serverId){const error=new Error();error.code="pairing_invalid";throw error;}await savePairing({...existing,hostUrl:transport.hostUrl,lastSeenAt:new Date().toISOString()});toast(t("addressUpdated"));}else{const paired=await transport.pair(serverId,await getDeviceId(),code);await savePairing({hostUrl:transport.hostUrl,serverId:paired.serverId,syncToken:paired.syncToken,pairedAt:paired.pairedAt,lastSeenAt:new Date().toISOString(),lastSyncAt:null});toast(t("paired"));}$("#pair-dialog").close();await checkComputer({retry:false});}catch(error){toast(userError(error,"secureConnectionFailed"));}finally{button.disabled=false;}}

  async function waitForOfflineShell(registration){if(!isSecureContext||!navigator.serviceWorker)return"unavailable";try{await Promise.race([registration?.active?.state==="activated"?Promise.resolve():new Promise((resolve,reject)=>{const worker=registration?.installing||registration?.waiting||registration?.active;if(!worker){reject(new Error());return;}const timer=setTimeout(()=>reject(new Error()),3000);const changed=()=>{if(worker.state==="activated"){clearTimeout(timer);worker.removeEventListener("statechange",changed);resolve();}};worker.addEventListener("statechange",changed);changed();})]);if(!registration?.active||!self.caches)return"unavailable";return await caches.match(new URL("./index.html",location.href).href)?"ready":"unavailable";}catch{return"unavailable";}}
  async function init(){document.documentElement.lang=getLocale();$("#sheet-close").addEventListener("click",()=>$("#capture-sheet").close());$("#pair-form").addEventListener("submit",pairComputer);$("#profile-file").addEventListener("change",event=>importProfile(event.target.files[0]));$("#receipt-file").addEventListener("change",event=>importReceipt(event.target.files[0]));addEventListener("lifeos:locale",refreshUI);const runtime=await initializeCaptureRuntime({secureContext:isSecureContext,indexedDbAvailable:Boolean(self.indexedDB),openDatabase:openDb,readDeviceId:getDeviceId,registerServiceWorker:self.navigator?.serviceWorker?()=>navigator.serviceWorker.register("./service-worker.js",{scope:"./"}):undefined});state.diagnostics.indexeddb=runtime.indexedDb;state.diagnostics.device=runtime.deviceId;state.diagnostics.storageError=runtime.storageError?"unavailable":"none";if(runtime.storageError){toast(t(runtime.indexedDb==="available"?"deviceIdUnavailable":"storageUnavailable"));return;}if(runtime.serviceWorker==="available"){state.diagnostics.serviceWorker="active";state.diagnostics.offlineShell=await waitForOfflineShell(runtime.serviceWorkerRegistration);}else{state.diagnostics.serviceWorker="unavailable";state.diagnostics.offlineShell="unavailable";}await refreshUI();setInterval(()=>{const clock=$("#timer-clock");get("state","activeTimer").then(row=>{if(clock&&row)clock.textContent=elapsed(row.value.startedAt);});},1000);addEventListener("online",()=>checkComputer({retry:false,auto:true}));addEventListener("offline",()=>{state.computer="offline";refreshUI();});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")checkComputer({retry:true,auto:true});});await checkComputer({retry:true,auto:true});}
  init().catch(error=>{state.lastErrorCode="initialization_failed";toast(userError(error,"initFailed"));});
})();
