(() => {
  "use strict";
  const zh = {
    navToday:"今日",navCapture:"记录",navPending:"待同步",navSettings:"设置",navigation:"主导航",today:"今日",capture:"记录",pending:"待同步",settings:"设置",close:"关闭",cancel:"取消",save:"保存",remove:"删除",details:"查看详情",
    computerOnline:"电脑在线",computerOffline:"电脑离线",computerUnpaired:"尚未连接电脑",allSynced:"已全部同步",pendingCount:"{count} 条待同步",pendingHeadline:"有 {count} 条记录等待同步",offlineReady:"离线可用",onDevice:"保存在本机",
    activeSession:"正在进行",noActiveSession:"现在没有进行中的记录",quickCapture:"快速记录",quickCaptureHelp:"高频操作，点开即可记录。",todayActivity:"今日记录",noTodayActivity:"今天还没有本机记录。",
    mood:"心情",meal:"饮食",habit:"习惯",task:"任务",note:"随手记",journal:"日记",english:"英语",workout:"健身",sleep:"睡眠",nap:"午睡",daily:"日常",learning:"学习",health:"健康",writing:"记录",captureSubtitle:"选择一项，几秒钟完成记录。",
    moodQuestion:"今天感觉怎么样？",moodTags:"标签（可选）",moodTagsPlaceholder:"平静、专注",moodNote:"想补充什么？（可选）",moodSave:"保存心情",moodRequired:"请选择一个心情分数。",
    mealQuestion:"记录哪一餐？",breakfast:"早餐",lunch:"午餐",dinner:"晚餐",snack:"加餐",mealSaved:"已记录饮食。",mealTypeRequired:"请选择餐别。",mealContent:"吃了什么？",mealContentPlaceholder:"例如：米饭、鸡胸肉、西兰花、牛奶……",mealTags:"快速标签（可选）",fullnessOptional:"饱腹感（可选）",notFull:"没吃饱",veryFull:"很撑",mealTime:"用餐时间",mealNote:"备注（可选）",mealNotePlaceholder:"口味、地点、吃完后的感觉……",mealSave:"记录饮食",mealTag_light:"清淡",mealTag_greasy:"油腻",mealTag_highProtein:"高蛋白",mealTag_highSugar:"高糖",mealTag_takeaway:"外卖",mealTag_canteen:"食堂",mealTag_home:"在家",
    habitNoProfile:"还没有习惯配置",habitNoProfileHelp:"从电脑导入记录配置后，可以在这里快速打卡。",importProfile:"从电脑导入记录配置",habitDone:"习惯已打卡。",
    taskName:"任务名称",dateOptional:"日期（可选）",noteOptional:"备注（可选）",taskSave:"创建任务",taskSaved:"任务已保存。",
    quickNotePlaceholder:"记点什么……",noteSave:"保存随手记",noteSaved:"随手记已保存。",titleOptional:"标题（可选）",content:"正文",tagsOptional:"标签（可选）",journalSave:"保存日记",journalSaved:"日记已保存。",
    course:"课程",coursePlaceholder:"新概念英语第二册",category:"类型",startLearning:"开始学习",startWorkout:"开始训练",startSleep:"开始睡眠",startNap:"开始午睡",trainingPart:"训练部位",timerAlreadyRunning:"已有一项计时正在进行，请先结束或取消。",
    inProgress:"进行中",studying:"学习中",training:"训练中",sleeping:"睡眠中",napping:"午睡中",startedAt:"开始于 {time}",finish:"结束",wakeUp:"醒来",finishNap:"结束午睡",cancelSession:"取消记录",cancelSessionConfirm:"确定取消这次计时吗？开始时间将不会保存。",
    finishEnglish:"结束英语学习",finishWorkout:"结束训练",finishSleep:"结束睡眠",finishNapTitle:"结束午睡",qualityOptional:"质量（可选）",sessionNoteOptional:"备注（可选）",keepRunning:"继续计时",saveSession:"保存记录",sessionSaved:"计时记录已保存。",
    chest:"胸",back:"背",shoulders:"肩",arms:"手臂",legs:"腿",core:"核心",fullBody:"全身",cardio:"有氧",other:"其他",courseCategory:"课程",listening:"听力",speaking:"口语",reading:"阅读",vocabulary:"词汇",writingCategory:"写作",youtube:"YouTube",podcast:"播客",
    syncCenter:"同步中心",syncOnlineReady:"电脑在线，可以同步。",syncOfflineHelp:"记录已安全保存在此设备，电脑上线后再同步即可。",syncUnpairedHelp:"先在设置中连接电脑，也可以继续离线记录。",syncNow:"立即同步",syncing:"正在同步…",syncedCount:"已同步 {count} 条记录",noPending:"所有记录都已同步",pendingList:"待同步记录",pendingEmpty:"没有等待同步的记录。",computerTemporarilyUnavailable:"电脑暂时不可用",
    removePendingConfirm:"删除后无法通过 LifeOS 恢复这条尚未同步的记录。确定删除吗？",removed:"记录已删除。",directSyncUnavailable:"暂时无法直接同步",useBundle:"请使用同步包，记录不会被删除。",
    bundleQuestion:"无法直接同步？",bundleHelp:"仅在电脑无法直连时使用。",bundleHelpRefined:"仅在无法通过电脑直接同步时使用。",exportBundle:"导出同步包",importReceipt:"导入同步回执",exported:"同步包已导出，请在电脑 LifeOS 中导入。",noEventsToExport:"没有待同步记录。",confirmImport:"确认电脑已导入",manualFallback:"手动确认已导入的批次",noBatches:"没有已导出的批次",markSynced:"标记为已同步",manualConfirmPrompt:"仅在电脑确认导入成功后继续。请输入 SYNCED。",batchKept:"记录仍保留在本机。",receiptConfirmed:"已确认 {count} 条记录同步完成。",syncPreview:"共 {count} 条 · {newCount} 条新记录",
    language:"语言",simplifiedChinese:"简体中文",englishLanguage:"English",computerConnection:"电脑连接",connected:"已连接",notConnected:"未连接",computerAddress:"电脑地址",connectComputer:"连接电脑",updateComputer:"更新电脑",openFullLifeOS:"打开完整 LifeOS",autoSync:"打开页面时自动同步",autoSyncHelp:"仅在页面打开且电脑在线时运行。",
    captureProfile:"记录配置",profileImported:"已导入 {count} 个习惯 · {time}",profileMissing:"尚未导入记录配置。",importProfileShort:"导入配置",defaultProfile:"当前使用默认记录配置",defaultProfileHelp:"可从电脑 LifeOS 导入你的习惯和偏好设置。",personalizedProfile:"已使用 LifeOS 个性化配置 · {time}",personalizedProfileHelp:"包含 {count} 个习惯。",importPersonalizedProfile:"导入个性化配置",dataSafety:"数据安全",dataSafetyText:"未同步的记录只保存在这台设备上。建议定期导出同步包作为额外副本。",advanced:"高级信息",diagnostics:"诊断信息",storageWarning:"系统可能在存储压力下清理浏览器数据。重要记录请导出同步包。",
    indexedDb:"IndexedDB",secureContext:"安全上下文",serviceWorker:"Service Worker",offlineShell:"离线外壳",deviceId:"设备 ID",computer:"电脑",pendingDiagnostic:"待同步",storageError:"存储错误",available:"可用",unavailable:"不可用",yes:"是",no:"否",ready:"已就绪",activated:"已激活",checking:"检查中",none:"无",errorCode:"错误代码",serverId:"Server ID",
    pairTitle:"连接电脑",lifeosComputerUrl:"LifeOS 电脑地址",serverIdLabel:"电脑标识",pairingCode:"一次性配对码",pairingCodeHelp:"请在电脑 LifeOS → 设置 → 数据中生成。更新同一台电脑的地址时可留空。",pairSave:"连接 / 更新",paired:"电脑连接成功。",addressUpdated:"电脑地址已更新。",
    savedOnDevice:"已保存在这台设备上。",storageUnavailable:"无法使用本地存储，记录可能无法保存。",deviceIdUnavailable:"无法准备设备标识。",initFailed:"记录器初始化失败。",secureConnectionFailed:"无法建立安全连接，请检查电脑是否在线、证书是否受信任，以及本地网络权限。",networkError:"暂时无法连接电脑。",originRejected:"当前页面没有权限连接这台电脑。",pairingInvalid:"配对码不正确，请重新生成。",pairingExpired:"配对码已过期，请生成新的配对码。",pairingRevoked:"这台设备的连接已失效，请重新配对。",serverMismatch:"连接到的不是原来那台 LifeOS 电脑，请重新连接。",invalidFile:"文件格式不正确。",fileTooLarge:"请选择小于 2 MB 的 JSON 文件。",genericError:"操作没有完成，请稍后重试。",
    detailTitle:"记录详情",durationMinutes:"{count} 分钟",timeAt:"{time}",profileImportSuccess:"记录配置已导入。",receiptInvalid:"同步回执无效或与当前批次不匹配。",deleteBatchConfirm:"只应在 LifeOS 已确认导入后清除这批记录。",
    moodHelp:"几秒钟记录当前感受",mealHelp:"记录餐别、内容与感受",habitHelp:"完成今天的习惯",taskHelp:"快速添加一项任务",noteHelp:"立即记下一个想法",journalHelp:"写下今天发生的事",englishHelp:"开始一段英语学习",workoutHelp:"开始一段健身训练",sleepHelp:"开始记录今晚睡眠",napHelp:"开始记录一次午睡",statusOfflineInstallHttp:"HTTP 下无法安装离线应用",statusRegisteredActive:"已注册 / 已激活",statusRegistered:"已注册",statusShellUnavailable:"不可用"
  };
  const en = {
    navToday:"Today",navCapture:"Capture",navPending:"Pending",navSettings:"Settings",navigation:"Main navigation",today:"Today",capture:"Capture",pending:"Pending",settings:"Settings",close:"Close",cancel:"Cancel",save:"Save",remove:"Remove",details:"View details",
    computerOnline:"Computer available",computerOffline:"Computer unavailable",computerUnpaired:"Not connected",allSynced:"All synced",pendingCount:"{count} pending",pendingHeadline:"{count} records waiting to sync",offlineReady:"Offline ready",onDevice:"On this device",
    activeSession:"Active session",noActiveSession:"No session is running",quickCapture:"Quick capture",quickCaptureHelp:"Your frequent actions, ready in one tap.",todayActivity:"Today's activity",noTodayActivity:"No captures on this device today.",
    mood:"Mood",meal:"Meals",habit:"Habit",task:"Task",note:"Quick note",journal:"Journal",english:"English",workout:"Workout",sleep:"Sleep",nap:"Nap",daily:"Daily",learning:"Learning",health:"Health",writing:"Writing",captureSubtitle:"Choose one and capture it in seconds.",
    moodQuestion:"How are you feeling today?",moodTags:"Tags (optional)",moodTagsPlaceholder:"Calm, focused",moodNote:"Anything to add? (optional)",moodSave:"Save mood",moodRequired:"Choose a mood score first.",
    mealQuestion:"Which meal?",breakfast:"Breakfast",lunch:"Lunch",dinner:"Dinner",snack:"Snack",mealSaved:"Meal recorded.",mealTypeRequired:"Choose a meal type.",mealContent:"What did you eat?",mealContentPlaceholder:"For example: rice, chicken, broccoli, milk…",mealTags:"Quick tags (optional)",fullnessOptional:"Fullness (optional)",notFull:"Not full",veryFull:"Very full",mealTime:"Meal time",mealNote:"Note (optional)",mealNotePlaceholder:"Taste, place, or how you felt afterward…",mealSave:"Record meal",mealTag_light:"Light",mealTag_greasy:"Greasy",mealTag_highProtein:"High protein",mealTag_highSugar:"High sugar",mealTag_takeaway:"Takeaway",mealTag_canteen:"Canteen",mealTag_home:"At home",habitNoProfile:"No habit profile yet",habitNoProfileHelp:"Import a Capture Profile from your computer to check in here.",importProfile:"Import Capture Profile",habitDone:"Habit completed.",
    taskName:"Task name",dateOptional:"Date (optional)",noteOptional:"Note (optional)",taskSave:"Create task",taskSaved:"Task saved.",quickNotePlaceholder:"Write something…",noteSave:"Save note",noteSaved:"Note saved.",titleOptional:"Title (optional)",content:"Content",tagsOptional:"Tags (optional)",journalSave:"Save journal",journalSaved:"Journal saved.",
    course:"Course",coursePlaceholder:"New Concept English II",category:"Category",startLearning:"Start learning",startWorkout:"Start workout",startSleep:"Start sleep",startNap:"Start nap",trainingPart:"Body part",timerAlreadyRunning:"Another timer is running. Finish or cancel it first.",inProgress:"In progress",studying:"Studying",training:"Training",sleeping:"Sleeping",napping:"Napping",startedAt:"Started {time}",finish:"Finish",wakeUp:"Wake up",finishNap:"Finish nap",cancelSession:"Cancel session",cancelSessionConfirm:"Cancel this timer? Its start time will not be saved.",
    finishEnglish:"Finish English",finishWorkout:"Finish workout",finishSleep:"Finish sleep",finishNapTitle:"Finish nap",qualityOptional:"Quality (optional)",sessionNoteOptional:"Note (optional)",keepRunning:"Keep running",saveSession:"Save session",sessionSaved:"Session saved.",chest:"Chest",back:"Back",shoulders:"Shoulders",arms:"Arms",legs:"Legs",core:"Core",fullBody:"Full body",cardio:"Cardio",other:"Other",courseCategory:"Course",listening:"Listening",speaking:"Speaking",reading:"Reading",vocabulary:"Vocabulary",writingCategory:"Writing",youtube:"YouTube",podcast:"Podcast",
    syncCenter:"Sync center",syncOnlineReady:"Your computer is available.",syncOfflineHelp:"Captures are safe on this device and can sync when your computer is online.",syncUnpairedHelp:"Connect a computer in Settings, or keep capturing offline.",syncNow:"Sync now",syncing:"Syncing…",syncedCount:"Synced {count} records",noPending:"All records are synced",pendingList:"Pending records",pendingEmpty:"Nothing is waiting to sync.",computerTemporarilyUnavailable:"Computer temporarily unavailable",removePendingConfirm:"Once removed, LifeOS cannot recover this unsynced record. Remove it?",removed:"Capture removed.",directSyncUnavailable:"Direct sync is temporarily unavailable",useBundle:"Use a Sync Bundle instead. Your captures were kept.",
    bundleQuestion:"Can't sync directly?",bundleHelp:"Use these only when your computer cannot connect directly.",bundleHelpRefined:"Use this only when direct computer sync is unavailable.",exportBundle:"Export Sync Bundle",importReceipt:"Import receipt",exported:"Bundle exported. Import it in LifeOS on your computer.",noEventsToExport:"There are no pending records.",confirmImport:"Confirm a computer import",manualFallback:"Manually confirm an exported batch",noBatches:"No exported batches",markSynced:"Mark synced",manualConfirmPrompt:"Continue only after LifeOS confirms the import. Type SYNCED.",batchKept:"Records remain on this device.",receiptConfirmed:"Confirmed {count} synced records.",syncPreview:"{count} total · {newCount} new",
    language:"Language",simplifiedChinese:"简体中文",englishLanguage:"English",computerConnection:"Computer connection",connected:"Connected",notConnected:"Not connected",computerAddress:"Computer address",connectComputer:"Connect computer",updateComputer:"Update computer",openFullLifeOS:"Open full LifeOS",autoSync:"Auto-sync while this page is open",autoSyncHelp:"Runs only while the page is open and your computer is available.",captureProfile:"Capture profile",profileImported:"{count} habits · imported {time}",profileMissing:"No Capture Profile imported.",importProfileShort:"Import profile",defaultProfile:"Using the default capture setup",defaultProfileHelp:"Import your habits and preferences from LifeOS on your computer.",personalizedProfile:"Using your LifeOS setup · {time}",personalizedProfileHelp:"Includes {count} habits.",importPersonalizedProfile:"Import personalized setup",dataSafety:"Data safety",dataSafetyText:"Unsynced captures exist only on this device. Export a Sync Bundle for an extra copy.",advanced:"Advanced",diagnostics:"Diagnostics",storageWarning:"The system may clear browser storage under pressure. Export important pending captures.",
    indexedDb:"IndexedDB",secureContext:"Secure context",serviceWorker:"Service Worker",offlineShell:"Offline shell",deviceId:"Device ID",computer:"Computer",pendingDiagnostic:"Pending",storageError:"Storage error",available:"Available",unavailable:"Unavailable",yes:"Yes",no:"No",ready:"Ready",activated:"Active",checking:"Checking",none:"None",errorCode:"Error code",serverId:"Server ID",
    pairTitle:"Connect your computer",lifeosComputerUrl:"LifeOS computer URL",serverIdLabel:"Server ID",pairingCode:"One-time pairing code",pairingCodeHelp:"Generate it in LifeOS → Settings → Data. Leave blank only when updating the address of the same computer.",pairSave:"Connect / update",paired:"Computer connected.",addressUpdated:"Computer address updated.",
    savedOnDevice:"Saved on this device.",storageUnavailable:"Local storage is unavailable. Captures may not be saved.",deviceIdUnavailable:"Unable to prepare this device ID.",initFailed:"Capture could not start.",secureConnectionFailed:"A secure connection could not be made. Check the computer, CA trust, and Local Network permission.",networkError:"Your computer cannot be reached right now.",originRejected:"This page is not allowed to connect to the computer.",pairingInvalid:"The pairing code is incorrect. Generate a new one.",pairingExpired:"The pairing code expired. Generate a new one.",pairingRevoked:"This device connection was revoked. Pair again.",serverMismatch:"A different LifeOS computer answered. Connect again.",invalidFile:"This file is not valid.",fileTooLarge:"Choose a JSON file smaller than 2 MB.",genericError:"That action did not finish. Try again.",
    detailTitle:"Capture details",durationMinutes:"{count} min",timeAt:"{time}",profileImportSuccess:"Capture Profile imported.",receiptInvalid:"The receipt is invalid or does not match this batch.",deleteBatchConfirm:"Clear this batch only after LifeOS confirms its import.",moodHelp:"Capture how you feel in seconds",mealHelp:"Record the meal, food, and how it felt",habitHelp:"Complete today's habit",taskHelp:"Quickly add a task",noteHelp:"Save a thought immediately",journalHelp:"Write down what happened today",englishHelp:"Start an English study session",workoutHelp:"Start a workout session",sleepHelp:"Start tracking tonight's sleep",napHelp:"Start tracking a nap",statusOfflineInstallHttp:"Offline install unavailable on HTTP",statusRegisteredActive:"Registered / Active",statusRegistered:"Registered",statusShellUnavailable:"Unavailable"
  };
  const messages = { "zh-CN": zh, en };
  let locale = "zh-CN";
  try { const saved = localStorage.getItem("lifeos-capture-locale"); if (saved === "zh-CN" || saved === "en") locale = saved; } catch { /* Chinese remains the deterministic default. */ }
  function t(key, values = {}) { const template = messages[locale][key] ?? zh[key] ?? key; return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template); }
  function setLocale(next) { if (next !== "zh-CN" && next !== "en") return; locale = next; try { localStorage.setItem("lifeos-capture-locale", next); } catch { /* Session-only fallback. */ } document.documentElement.lang = next; dispatchEvent(new CustomEvent("lifeos:locale", { detail: next })); }
  function formatDate(date, options) { return new Intl.DateTimeFormat(locale === "zh-CN" ? "zh-CN" : "en-US", options).format(date); }
  self.LifeOSCaptureI18n = { t, setLocale, getLocale: () => locale, formatDate, messages };
})();
